### PR TITLE
Create Dijkstra’s Shortest Path Algorithm.cpp

### PR DESCRIPTION
**Pull request by samyak260702**

### CODE REVIEW

**Review by jvm-coder — APPROVED** [review]

**Review by jvm-coder — COMMENTED** [review]
Add data to CONTRIBUTING.md

**Comment by jvm-coder** [comment]
Add your details to the CONTRIBUTING.md file

**Comment by samyak260702** [comment]
how should i do that now can you please tell should i do another pull request or what

**Comment by jvm-coder** [comment]
> how should i do that now can you please tell should i do another pull request or what

You can do this in the same PR, or you can create another PR for that

**Pull request merged**
