### PR TITLE
Machine Learning Implementation Example

### PR DESCRIPTION
**Pull request by Anushka-codergirl**
Image Classification

### CODE REVIEW

**Comment by jvm-coder** [comment]
Please add details to CONTRIBUTING.md file to get your PR approved.

**Comment by Anushka-codergirl** [comment]
Okay!

**Comment by Anushka-codergirl** [comment]
Done!

**Comment by jvm-coder** [comment]
Thanks for the contribution

**Comment by Anushka-codergirl** [comment]
It's my pleasure. Can you please add a hacktoberfest-accepted label?

**Pull request merged**
