### PR TITLE
Applet awt Calculator added

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
Signed-off-by: dhruv dhruvpatidar35@gmail.com
This PR adds a Calculator that uses Applet in java

### CODE REVIEW

**Comment by jvm-coder** [comment]
Add data to CONTRIBUTING.md file also for getting your PR qualified for Hacktoberfest

**Comment by dhruvpatidar359** [comment]
i have already added this in some another PR so there is no need to merge it  , as it will duplicates the code for the calculator #70

**Comment by dhruvpatidar359** [comment]
One more thing i want to ask that, is it necessary to update contributing.md , everytime i conrtibute to the repo ? @jvm-coder

**Review by jvm-coder — APPROVED** [review]

**Comment by jvm-coder** [comment]
> One more thing i want to ask that, is it necessary to update contributing.md , everytime i conrtibute to the repo ? @jvm-coder

No, you have put your details only one time, so that we get a record of all the contributors and thank you so much for your contribution.

**Pull request merged**
